//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust
    {
        public int CustID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> BookID { get; set; }
        public string Email { get; set; }
    }
}
